imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:

  server:
    sources:
      functionshost:
        localFolder: '{{HostLocation}}'
    project: functionshost/WebApi.csproj
    readyStateText: 'Application started.'
    environmentVariables:
      ASPNETCORE_URLS: '{{ AspNetUrls }}'

scenarios:
  hellohttp:
    webapp:
      job: server
        
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /api/hello

profiles:
  win2022:
    variables:
      serverUri: http://{{ CrankAgentAppVm }}
      serverPort: 5000
    jobs: 
      webapp:
        endpoints: 
          - http://{{ CrankAgentAppVm }}:5010
      load:
        endpoints: 
          - http://{{ CrankAgentLoadVm }}:5010
