name: Close stale issues
description: Action to handle stale issues
resource: repository
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Close stale issues
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - hasLabel:
          label: no-recent-activity
      - noActivitySince:
          days: 3
      - isNotLabeledWith:
          label: 'bot: do not close'
      actions:
      - closeIssue
onFailure: 
onSuccess: 