name: Flag stale issues due to no activity
description: Flag issues that have seen no activity in over three years.
resource: repository
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - frequencies:
      - weekday:
          day: Monday
          time: 10:00
      filters:
      - isIssue
      - isOpen
      - noActivitySince:
          days: 1095 # 3 years
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: >-
            This issue has been automatically marked as stale because it has not seen any activity for **3 years**. It will be closed if no further activity occurs **within 3 days of this comment**.


            If you are not the original author (${issueAuthor}) and believe this issue is not stale, please comment with `/bot not-stale` and I will not close it.
onFailure:
onSuccess: