name: Flag stale issues
description: Flag issues that have seen no activity in over three years.
resource: repository
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - frequencies:
      - weekday:
          day: Monday
          time: 10:00
      filters:
      - isIssue
      - isOpen
      - noActivitySince:
          days: 1095 # 3 years
      - isNotLabeledWith:
          label: 'Needs: Author Feedback'
      actions:
      - addLabel:
          label: 'Needs: Author Feedback'
      - addReply:
          reply: >-
            This issue has been automatically marked as stale because it has not seen any activity for **3 years**. It will be closed if no further activity occurs **within 5 days of this comment**.
            If you believe this issue is still relevant, please leave a comment with details.
onFailure:
onSuccess:
