name: Flag stale issues
description: Flag issues that have seen no activity in over three years.
resource: repository
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - frequencies:
      - weekday:
          day: Monday
          time: 10:00
      filters:
      - isIssue
      - isOpen
      - noActivitySince:
          days: 1095 # 3 years
      - isNotLabeledWith:
          label: 'Needs: Author Feedback'
      actions:
      - addLabel:
          label: 'Needs: Author Feedback'
onFailure:
onSuccess:
