variables:
  ${{ if not(contains(variables['Build.SourceBranch'], '/release/analyzers/' )) }}:
      buildNumberTemp: $(Build.BuildNumber)
  ${{ if contains(variables['Build.SourceBranch'], '/release/analyzers/' ) }}:
      isReleaseBuildTemp: true
  buildNumber: $[variables.buildNumberTemp]
  isReleaseBuild: $[variables.isReleaseBuildTemp]
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pr:
  branches:
    include:
    - dev
    - release/analyzers/*
  paths:
    include:
    - src/WebJobs.Script.Analyzers/*
    - test/WebJobs.Script.Tests.Analyzers/*

trigger:
  branches:
    include:
    - dev
    - release/analyzers/*
  paths:
    include:
    - src/WebJobs.Script.Analyzers/*
    - test/WebJobs.Script.Tests.Analyzers/*

jobs:
- job: BuildTestPack
  pool:
    name: '1ES-Hosted-AzFunc'
    demands:
      - ImageOverride -equals MMS2022TLS
  steps:
  - task: 1ESHostedPoolValidation@1  
  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      arguments: '-c Release'
      projects: 'src/WebJobs.Script.Analyzers/WebJobs.Script.Analyzers.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      arguments: '-c Release'
      projects: 'test/**/WebJobs.Script.Tests.Analyzers.csproj'
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
    displayName: 'ESRP CodeSigning: Authenticode'
    condition: eq(variables.isReleaseBuild, true)
    inputs:
      ConnectedServiceName: 'ESRP Service'
      FolderPath: 'src\WebJobs.Script.Analyzers\bin\Release'
      Pattern: Microsoft.Azure.Functions.Analyzers.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]
  - task: DotNetCoreCLI@2
    displayName: 'Build packages'
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: '--no-build -c Release -o packages -p:BuildNumber=$(buildNumber) -p:CommitHash=$(Build.SourceVersion)'
      projects: |
        **\WebJobs.Script.Analyzers.csproj
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
    displayName: 'ESRP CodeSigning: Nupkg'
    condition: eq(variables.isReleaseBuild, true)
    inputs:
      ConnectedServiceName: 'ESRP Service'
      FolderPath: 'packages'
      Pattern: 'Microsoft.Azure.Functions.Analyzers*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetSign",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
        ]
  - task: DeleteFiles@1
    displayName: 'Delete CodeSignSummary files'
    condition: eq(variables.isReleaseBuild, true)
    inputs:
      contents: '**\CodeSignSummary-*.md'
  - publish: $(System.DefaultWorkingDirectory)/packages
    artifact: drop

