module.exports = function (context, timerInfo) {
    var timeStamp = new Date().toISOString();
    context.log('Node.js timer trigger function ran! ' + timeStamp);

    console.log('PastDue: ' + timerInfo.isPastDue);
    console.log('Last: ' + timerInfo.last);
    console.log('Next: ' + timerInfo.next);

    context.bindings.message = {
        id: Math.floor(Math.random() * 10000) + 1,
        notes: "Generated by Timer function"
    };

    context.done();
}