version: '{build}'

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - dev

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_VERSION: 2.1.402
  
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0    

install:
  - ps: | 
        Get-Command mvn  
        Get-Command nuget
  - cmd: |
        mvn -v
        echo %JAVA_HOME%
        dotnet --info
        npm i -g azure-functions-core-tools
  
before_build:
  - ps: |
        nuget restore WebJobs.Script.Tests.Perf.sln -Verbosity quiet
        cd .\test\WebJobs.Script.Tests.Perf\Artifacts\PS
        .\build-jar.ps1

build:
  project: WebJobs.Script.Tests.Perf.sln