// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Blobs.Bindings.BlobContainerBinding.#Access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Blobs.CloudBlobContainerArgumentBindingProvider+CloudBlobContainerArgumentBinding.#Access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Blobs.CloudBlobContainerArgumentBindingProvider+CloudBlobContainerArgumentBinding.#Access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Blobs.CloudBlobEnumerableArgumentBindingProvider+CloudBlobEnumerableArgumentBinding.#Access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Blobs.CloudBlobEnumerableArgumentBindingProvider+CloudBlobEnumerableArgumentBinding.#Access")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CloudQueue", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.StorageClientFactory.#CreateCloudQueueClient(Microsoft.Azure.WebJobs.Host.StorageClientFactoryContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.PropertyHelper.#.ctor(System.Reflection.PropertyInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "PropertyType", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.PropertyHelper.#PropertyType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.PropertyHelper.#MakeFastPropertySetter`1(System.Reflection.PropertyInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "IsDisabled", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Listeners.HostListenerFactory.#IsDisabledByProvider(System.Type,System.Reflection.MethodInfo,Microsoft.Azure.WebJobs.Host.IJobActivator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "MethodInfo", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Listeners.HostListenerFactory.#IsDisabledByProvider(System.Type,System.Reflection.MethodInfo,Microsoft.Azure.WebJobs.Host.IJobActivator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Loggers.FastLoggerProvider.#Microsoft.Azure.WebJobs.Host.Loggers.IFunctionOutputLogger.CreateAsync(Microsoft.Azure.WebJobs.Host.Executors.IFunctionInstance,System.Threading.CancellationToken)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Azure.WebJobs.Host.Loggers.FastTableLoggerProvider.#Microsoft.Azure.WebJobs.Host.Loggers.IFunctionOutputLogger.CreateAsync(Microsoft.Azure.WebJobs.Host.Executors.IFunctionInstance,System.Threading.CancellationToken)")]
