<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Microsoft.Azure.WebJobs.Script.Rpc</PackageId>
    <AssemblyName>Microsoft.Azure.WebJobs.Script.Rpc</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Script.Rpc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebJobs.Script\WebJobs.Script.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
  </ItemGroup>

</Project>
