<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--<Nullable>enable</Nullable>-->
    <PackageId>Microsoft.Azure.Functions.WorkerModel</PackageId>
    <AssemblyName>Microsoft.Azure.Functions.WorkerModel</AssemblyName>
    <RootNamespace>Microsoft.Azure.Functions.WorkerModel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.55.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include=".\azure-functions-language-worker-protobuf\src\proto\**\*.proto" GrpcServices="server" ProtoRoot=".\azure-functions-language-worker-protobuf\src\proto" Access="Internal" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebJobs.Script\WebJobs.Script.csproj" />
  </ItemGroup>

</Project>
