imports:
  - https://raw.githubusercontent.com/dotnet/crank/master/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  functionsServer:
    source:
      repository: https://github.com/Azure/azure-functions-host
      branchOrCommit: "{{ BranchOrCommit }}"
      project: src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj
    readyStateText: Application started.
  aspnetServer:
    source:
      repository: https://github.com/Azure/azure-functions-host
      branchOrCommit: "{{ BranchOrCommit }}"
      project: tools/Crank/BenchmarkApps/AspNetBenchmark/AspNetBenchmark/AspNetBenchmark.csproj
    readyStateText: Application started.

scenarios:
  http:
    application:
      job: functionsServer
      environmentVariables:
        AzureWebJobsScriptRoot: "{{ FunctionAppPath }}"
        ASPNETCORE_URLS: "{{ AspNetUrls }}"
    load:
      job: bombardier
      variables:
        path: /api/Hello
  http-appsvc:
    application:
      job: functionsServer
      environmentVariables:
        HOME: "{{ HomePath }}"
        WEBSITE_SITE_NAME: "Test"
        WEBSITE_INSTANCE_ID: "8399B720-AB73-46D6-94DE-5A27871B3155"
        WEBSITE_OWNER_NAME: "A5F47496-A284-4788-A127-E79454330567+westuswebspace"
        ASPNETCORE_URLS: "{{ AspNetUrls }}"
    load:
      job: bombardier
      variables:
        path: /api/Hello
  http-linux-appsvc:
    application:
      job: functionsServer
      environmentVariables:
        HOME: "{{ HomePath }}"
        WEBSITE_SITE_NAME: "Test"
        WEBSITE_INSTANCE_ID: "8399B720-AB73-46D6-94DE-5A27871B3155"
        WEBSITE_OWNER_NAME: "A5F47496-A284-4788-A127-E79454330567+westuswebspace"
        FUNCTIONS_LOGS_MOUNT_PATH: "{{ TempLogPath }}"
        ASPNETCORE_URLS: "{{ AspNetUrls }}"
    load:
      job: bombardier
      variables:
        path: /api/Hello
  aspnet-hello:
    application:
      job: aspnetServer
      environmentVariables:
        ASPNETCORE_URLS: "{{ AspNetUrls }}"
    load:
      job: bombardier
      variables:
        path: /api/Hello

profiles:
  default:
    variables:
      serverUri: http://{{ CrankAgentAppVm }}
      serverPort: 5000
    jobs: 
      application:
        endpoints: 
          - "http://{{ CrankAgentAppVm }}:5010"
      load:
        endpoints: 
          - "http://{{ CrankAgentLoadVm }}:5010"
