//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.WebJobs.Script.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.WebJobs.Script.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your function must contain a single public method, a public method named &apos;Run&apos;, or a public method matching the name specified in the &apos;entryPoint&apos; metadata property..
        /// </summary>
        internal static string DotNetFunctionEntryPointRulesMessage {
            get {
                return ResourceManager.GetString("DotNetFunctionEntryPointRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed downloading extension bundle from {0} to {1}.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading extension bundle from {0} to {1}.
        /// </summary>
        internal static string DownloadingZip {
            get {
                return ResourceManager.GetString("DownloadingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete an extension. Persistent file system not available in the current hosting environment.
        /// </summary>
        internal static string ErrorDeletingExtension {
            get {
                return ResourceManager.GetString("ErrorDeletingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading zip content {0}. Status Code:{1}. Reason:{2}.
        /// </summary>
        internal static string ErrorDownloadingZip {
            get {
                return ResourceManager.GetString("ErrorDownloadingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching version information for extension bundle {0}.
        /// </summary>
        internal static string ErrorFetchingVersionInfo {
            get {
                return ResourceManager.GetString("ErrorFetchingVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install an extension. Persistent file system not available in the current hosting environment.
        /// </summary>
        internal static string ErrorInstallingExtension {
            get {
                return ResourceManager.GetString("ErrorInstallingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find or download extension bundle.
        /// </summary>
        internal static string ErrorLoadingExtensionBundle {
            get {
                return ResourceManager.GetString("ErrorLoadingExtensionBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete extension when ExtensionBundles is configured..
        /// </summary>
        internal static string ExtensionBundleBadRequestDelete {
            get {
                return ResourceManager.GetString("ExtensionBundleBadRequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install extension when ExtensionBundles is configured..
        /// </summary>
        internal static string ExtensionBundleBadRequestInstall {
            get {
                return ResourceManager.GetString("ExtensionBundleBadRequestInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of id property in extensionBundle section of {0} file is invalid or missing. See https://aka.ms/functions-hostjson for more information.
        /// </summary>
        internal static string ExtensionBundleConfigMissingId {
            get {
                return ResourceManager.GetString("ExtensionBundleConfigMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id and version property are missing in extensionBundle section of {0} file. See https://aka.ms/functions-hostjson for more information&quot;.
        /// </summary>
        internal static string ExtensionBundleConfigMissingMessage {
            get {
                return ResourceManager.GetString("ExtensionBundleConfigMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of version property in extensionBundle section of {0} file is invalid or missing. See https://aka.ms/functions-hostjson for more information.
        /// </summary>
        internal static string ExtensionBundleConfigMissingVersion {
            get {
                return ResourceManager.GetString("ExtensionBundleConfigMissingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a matching extension bundle at {0}.
        /// </summary>
        internal static string ExtensionBundleFound {
            get {
                return ResourceManager.GetString("ExtensionBundleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting extension bundle at {0}.
        /// </summary>
        internal static string ExtractingBundleZip {
            get {
                return ResourceManager.GetString("ExtractingBundleZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching information on versions of extension bundle {0} available on {1}{2}.
        /// </summary>
        internal static string FetchingVersionInfo {
            get {
                return ResourceManager.GetString("FetchingVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting language worker channel specialization.
        /// </summary>
        internal static string LanguageWorkerChannelSpecializationTrace {
            get {
                return ResourceManager.GetString("LanguageWorkerChannelSpecializationTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Extension bundle from {0}.
        /// </summary>
        internal static string LoadingExtensionBundle {
            get {
                return ResourceManager.GetString("LoadingExtensionBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for extension bundle {0} at {1}.
        /// </summary>
        internal static string LocateExtensionBundle {
            get {
                return ResourceManager.GetString("LocateExtensionBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle version matching the {0} was not found.
        /// </summary>
        internal static string MatchingBundleNotFound {
            get {
                return ResourceManager.GetString("MatchingBundleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip extraction complete.
        /// </summary>
        internal static string ZipExtractionComplete {
            get {
                return ResourceManager.GetString("ZipExtractionComplete", resourceCulture);
            }
        }
    }
}
