<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Microsoft.Azure.WebJobs.Script.Tests.EnvironmentVariables.TestHost</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Script.Tests.EnvironmentVariables.TestHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/WebJobs.Script/WebJobs.Script.csproj" />
    <ProjectReference Include="../../src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj" />
    <ProjectReference Include="../WebJobs.Script.Tests.Shared/WebJobs.Script.Tests.Shared.csproj" />
    <Compile Include="../WebJobs.Script.Tests/Config/EnvironmentVariablesConfigurationTestContracts.cs"
             Link="EnvironmentVariablesConfigurationTestContracts.cs" />
    <Compile Include="../WebJobs.Script.Tests/Environment/EnvironmentProfileContract.cs"
             Link="EnvironmentProfileContract.cs" />
  </ItemGroup>

</Project>
