<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--<Nullable>enable</Nullable>-->
    <PackageId>Microsoft.Azure.Functions.InstanceManager</PackageId>
    <AssemblyName>Microsoft.Azure.Functions.InstanceManager</AssemblyName>
    <RootNamespace>Microsoft.Azure.Functions.InstanceManager</RootNamespace>
    <NoWarn>$(NoWarn);SA1633</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Azure.Functions.WorkerModel\Azure.Functions.WorkerModel.csproj" />
  </ItemGroup>

</Project>
