jobs:
- job: BuildArtifactsWindows
  displayName: Build Windows Artifacts

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022 
    os: windows

  variables:
    drop_path: $(Build.ArtifactStagingDirectory)
    nuget_drop_path: $(drop_path)/nuget
    windows_drop_path: $(drop_path)/windows

  templateContext:
    sdl:
      binskim:
        analyzeTargetGlob: "+:f|$(drop_path)\\**\\*.dll;+:f|$(drop_path)\\**\\*.exe;-:f|$(drop_path)\\**\\*MonoPosixHelper.dll;-:f|$(drop_path)\\**\\FunctionsNetHost.exe;-:f|$(drop_path)\\**\\grpc_csharp_ext.*.dll"
    outputParentDirectory: $(drop_path)
    outputs:
    - output: pipelineArtifact
      displayName: Publish site extension
      path: $(windows_drop_path)
      artifact: drop_windows
    - output: pipelineArtifact
      displayName: Publish nuget packages
      path: $(nuget_drop_path)
      artifact: drop_nuget

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self
  - template: /eng/ci/templates/steps/build-site-ext.yml@self
    parameters:
      publishDir: $(windows_drop_path)

  - task: DotNetCoreCLI@2
    displayName: Build host packages
    inputs:
      command: custom
      custom: pack
      arguments: -c release -o $(nuget_drop_path)
      projects: |
        **/WebJobs.Script.csproj
        **/WebJobs.Script.WebHost.csproj
        **/WebJobs.Script.Grpc.csproj

  - task: DotNetCoreCLI@2
    displayName: Build Abstractions and ExtensionsMetadataGenerator
    inputs:
      command: build
      arguments: '-c release'
      projects: |
        **/ExtensionsMetadataGenerator.csproj
        **/WebJobs.Script.Abstractions.csproj
