jobs:
- job: BuildArtifactsWindows
  displayName: Build Windows Artifacts

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022 
    os: windows

  variables:
    ${{ if or( eq( variables['Build.Reason'], 'PullRequest' ), and( not( contains( variables['Build.SourceBranch'], 'release/inproc6/4.' ) ), not( contains( variables['Build.SourceBranch'], 'release/inproc8/4.' ) ), not( contains( variables['Build.SourceBranch'], 'release/4.' ) ), not( contains( variables['Build.SourceBranch'], 'release/ExtensionsMetadataGenerator/' ) ) ) ) }}:
        packSuffixSwitchTemp: --version-suffix $(buildNumber)
        emgSuffixSwitchTemp: --version-suffix ci$(buildNumber)
    packSuffixSwitch: $[variables.packSuffixSwitchTemp]
    emgSuffixSwitch: $[variables.emgSuffixSwitchTemp]
    artifacts_path: $(Build.ArtifactStagingDirectory)
    log_dir: $(artifacts_path)/log
    nuget_package_path: $(artifacts_path)/NugetPackages

  templateContext:
    outputParentDirectory: $(artifacts_path)
    outputs:
    - output: pipelineArtifact
      displayName: Publish site extension
      path: $(artifacts_path)/SiteExtension
      artifact: SiteExtension
    - output: pipelineArtifact
      displayName: Publish private site extension
      path: $(artifacts_path)/PrivateSiteExtension
      artifact: PrivateSiteExtension
    - output: pipelineArtifact
      displayName: Publish site extension symbols
      path: $(artifacts_path)/Symbols
      artifact: Symbols
    - output: pipelineArtifact
      displayName: Publish nuget packages
      path: $(artifacts_path)/NugetPackages
      artifact: NugetPackages
    - output: pipelineArtifact
      displayName: Publish logs
      path: $(log_dir)
      artifact: Windows_Log
      sbomEnabled: false
      condition: always()

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Publish Site Extension
    inputs:
      command: custom
      custom: restore
      projects: src/WebJobs.Script.SiteExtension/WebJobs.Script.SiteExtension.proj
      arguments: '-v m -p:PublishReadyToRun=true -bl:$(log_dir)/restore.binlog'

  - task: DotNetCoreCLI@2
    displayName: Publish Site Extension
    inputs:
      command: custom
      custom: publish
      publishWebProjects: false # we use our own publish logic
      zipAfterPublish: false # we use our own zip logic
      projects: src/WebJobs.Script.SiteExtension/WebJobs.Script.SiteExtension.proj
      arguments: '-v m -c release --no-restore -p:BuildNumber=$(buildNumber) -p:MinorVersionPrefix=$(minorVersionPrefix) -p:ZipArtifactsPath=$(artifacts_path) -bl:$(log_dir)/publish.binlog'

  - task: DotNetCoreCLI@2
    displayName: Build host packages
    inputs:
      command: custom
      custom: pack
      arguments: -p:BuildNumber=$(buildNumber) -c release $(packSuffixSwitch) -o $(nuget_package_path)
      projects: |
        **/WebJobs.Script.csproj
        **/WebJobs.Script.WebHost.csproj
        **/WebJobs.Script.Grpc.csproj

  - task: DotNetCoreCLI@2
    displayName: Build Abstractions and ExtensionsMetadataGenerator
    inputs:
      command: build
      arguments: '-c release'
      projects: |
        **/ExtensionsMetadataGenerator.csproj
        **/WebJobs.Script.Abstractions.csproj

  - task: EsrpCodeSigning@2
    displayName: Sign Abstractions assemblies
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: out/bin/WebJobs.Script.Abstractions/release
      Pattern: Microsoft.Azure.WebJobs.Script.Abstractions*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: DotNetCoreCLI@2
    displayName: Pack Abstractions
    inputs:
      command: custom
      custom: pack
      arguments: '--no-build -c release -o $(nuget_package_path)'
      projects: |
        **/WebJobs.Script.Abstractions.csproj

  - task: EsrpCodeSigning@2
    displayName: Sign Abstractions package
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: $(nuget_package_path)
      Pattern: Microsoft.Azure.WebJobs.Script.Abstractions*.nupkg
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetSign",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
        ]

  - task: EsrpCodeSigning@2
    displayName: Sign ExtensionsMetadataGenerator assemblies
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: out/bin/ExtensionsMetadataGenerator
      Pattern: Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameSign",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameVerify",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: DotNetCoreCLI@2
    displayName: Pack ExtensionsMetadataGenerator
    inputs:
      command: custom
      custom: pack
      arguments: '--no-build -c release $(emgSuffixSwitch) -o $(nuget_package_path)'
      projects: |
        **/ExtensionsMetadataGenerator.csproj

  - task: EsrpCodeSigning@2
    displayName: Sign ExtensionsMetadataGenerator package
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: $(nuget_package_path)
      Pattern: Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator*.nupkg
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetSign",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'
