parameters:
- name: minorVersionPrefix
  type: string
  default: ''

- name: buildNumber
  type: string
  default: ''

jobs:
- job: BuildArtifactsLinux
  displayName: Build Linux Artifacts

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    # TODO: onboard to Azure Artifacts Drops to allow accessing this from mseng
    # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/azure-artifacts/artifact-services-onboarding
    - output: pipelineArtifact
      path: $(Build.ArtifactStagingDirectory)/Linux
      artifact: Linux

  pool:
    name: 1es-pool-azfunc
    image: 1es-ubuntu-22.04
    os: linux

  variables:
    project: src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj
    runtime: linux-x64
    buildArgs: > 
    -v m -c release -r $[variables.runtime] --self-contained true
    -p:BuildNumber=${{ parameters.buildNumber }}
    -p:MinorVersionPrefix=${{ parameters.minorVersionPrefix }}
    -p:IsPackable=false

  steps:
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate

  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: custom
      custom: restore
      projects: $(project)
      arguments: '-v m -r $(runtime) -p:PublishReadyToRun=true' # add PublishReadyToRun=true for https://github.com/dotnet/sdk/issues/20701

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: custom
      custom: build
      projects: $(project)
      arguments: '--no-restore $(buildArgs)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: custom
      custom: publish
      projects: $(project)
      arguments: '--no-build $(buildArgs)'

  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: out/pub/WebJobs.Script.WebHost/release_linux-x64/
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/Linux/WebJobs.Script.WebHost.$(Build.BuildId).zip

  - task: ManifestGeneratorTask@0
    displayName: 'SBOM Generation Task - Linux'
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)/Linux'
      Verbosity: 'Information'
