parameters:
- name: WorkerPackageName
  displayName: Worker Package Name
  type: string
  
- name: WorkerPackageVersion
  displayName: Worker Package Version
  type: string

jobs:
- job: WorkerSiteExtension
  displayName: Build Worker Site Extension

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows

  variables:
    drop_path: $(Build.ArtifactStagingDirectory)

  templateContext:
    outputParentDirectory: $(drop_path)
    outputs:
    - output: pipelineArtifact
      displayName: Publish artifacts
      path: $(drop_path)
      artifact: drop_windows

  steps:
  - task: DotNetCoreCLI@2
    displayName: Create site extension
    inputs:
      command: 'build'
      projects: 'src/WebJobs.Script.SiteExtension/GenerateWorkerSiteExtension.csproj'
      arguments : '-p:WorkerPackageName=${{ parameters.WorkerPackageName }} -p:WorkerPackageVersion=${{ parameters.WorkerPackageVersion }} -p:OutputDir="$(drop_path)"'