parameters:
- name: minorVersionPrefix
  type: string
  default: ''

jobs:
- job: BuildArtifactsLinux
  displayName: Build Linux Artifacts

  variables:
    project: src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj
    configuration: release
    runtime: linux-x64
    logDir: $(Build.ArtifactStagingDirectory)/log
    buildArgs: '-v m -c $(configuration) -r $(runtime) --self-contained true -p:BuildNumber=$(buildNumber) -p:MinorVersionPrefix=${{ parameters.minorVersionPrefix }} -p:IsPackable=false'
    publishDir: out/pub/WebJobs.Script.WebHost/$(configuration)_$(runtime)
    publishZip: $(Build.ArtifactStagingDirectory)/Linux/WebJobs.Script.WebHost.$(Build.BuildNumber).zip

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    # TODO: onboard to Azure Artifacts Drops to allow accessing this from docker linux pipeline in msazure
    # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/azure-artifacts/artifact-services-onboarding
    - output: pipelineArtifact
      displayName: Publish linux artifacts
      targetPath: $(publishZip)
      artifact: Linux
      sbomBuildDropPath: $(publishDir)
    - output: pipelineArtifact
      displayName: Publish logs
      path: $(logDir)
      artifact: Linux_Log
      sbomEnabled: false
      condition: always()

  pool:
    name: 1es-pool-azfunc
    image: 1es-ubuntu-22.04
    os: linux

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: custom
      custom: restore
      projects: $(project)
      arguments: '-v m -r $(runtime) -p:PublishReadyToRun=true -bl:$(logDir)/restore.binlog' # add PublishReadyToRun=true for https://github.com/dotnet/sdk/issues/20701

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: custom
      custom: build
      projects: $(project)
      arguments: '--no-restore $(buildArgs) -bl:$(logDir)/build.binlog'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: custom
      custom: publish
      publishWebProjects: false
      zipAfterPublish: false
      projects: $(project)
      arguments: '--no-build $(buildArgs) -bl:$(logDir)/publish.binlog'

  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: out/pub/WebJobs.Script.WebHost/release_linux-x64/
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(publishZip)
