parameters:
- name: minorVersionPrefix
  type: string
  default: ''

jobs:
- job: BuildArtifactsWindows
  displayName: Build Windows Artifacts

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish site extension
      path: $(Build.ArtifactStagingDirectory)/SiteExtension
      artifact: SiteExtension
    - output: pipelineArtifact
      displayName: Publish private site extension
      path: $(Build.ArtifactStagingDirectory)/PrivateSiteExtension
      artifact: PrivateSiteExtension
    - output: pipelineArtifact
      displayName: Publish site extension symbols
      path: $(Build.ArtifactStagingDirectory)/Symbols
      artifact: Symbols
    - output: pipelineArtifact
      displayName: Publish nuget packages
      path: $(Build.ArtifactStagingDirectory)/NugetPackages
      artifact: NugetPackages

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022 
    os: windows

  variables:
    ${{ if or( eq( variables['Build.Reason'], 'PullRequest' ), and( not( contains( variables['Build.SourceBranch'], 'release/inproc6/4.' ) ), not( contains( variables['Build.SourceBranch'], 'release/inproc8/4.' ) ), not( contains( variables['Build.SourceBranch'], 'release/4.' ) ), not( contains( variables['Build.SourceBranch'], 'release/ExtensionsMetadataGenerator/' ) ) ) ) }}:
        suffixTemp: $(buildNumber)
        packSuffixSwitchTemp: --version-suffix $(buildNumber)
        emgSuffixSwitchTemp: --version-suffix ci$(buildNumber)
    suffix: $[variables.suffixTemp] # this resolves to an empty string if it is missing
    packSuffixSwitch: $[variables.packSuffixSwitchTemp]
    emgSuffixSwitch: $[variables.emgSuffixSwitchTemp]

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: PowerShell@2
    displayName: Build artifacts
    inputs:
      filePath: build/build-extensions.ps1
      arguments: '-buildNumber "$(buildNumber)" -suffix "$(suffix)" -minorVersionPrefix "$(minorVersionPrefix)"'

  - task: CopyFiles@2
    inputs:
      SourceFolder: out/pub/WebJobs.Script.WebHost
      Contents: '**/*.zip'
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: DotNetCoreCLI@2
    displayName: Build host packages
    inputs:
      command: custom
      custom: pack
      arguments: -p:BuildNumber=$(buildNumber) -c release $(packSuffixSwitch)
      projects: |
        **/WebJobs.Script.csproj
        **/WebJobs.Script.WebHost.csproj
        **/WebJobs.Script.Grpc.csproj

  - task: DotNetCoreCLI@2
    displayName: Build Abstractions and ExtensionsMetadataGenerator
    inputs:
      command: build
      arguments: '-c release'
      projects: |
        **/ExtensionsMetadataGenerator.csproj
        **/WebJobs.Script.Abstractions.csproj

  - task: EsrpCodeSigning@2
    displayName: Sign Abstractions assemblies
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: out/bin/WebJobs.Script.Abstractions/release
      Pattern: Microsoft.Azure.WebJobs.Script.Abstractions*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: DotNetCoreCLI@2
    displayName: Pack Abstractions
    inputs:
      command: custom
      custom: pack
      arguments: '--no-build -c release'
      projects: |
        **/WebJobs.Script.Abstractions.csproj

  - task: EsrpCodeSigning@2
    displayName: Sign Abstractions package
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: out/pkg/release
      Pattern: Microsoft.Azure.WebJobs.Script.Abstractions*.nupkg
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetSign",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
        ]

  - task: EsrpCodeSigning@2
    displayName: Sign ExtensionsMetadataGenerator assemblies
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: out/bin/ExtensionsMetadataGenerator
      Pattern: Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameSign",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameVerify",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: DotNetCoreCLI@2
    displayName: Pack ExtensionsMetadataGenerator
    inputs:
      command: custom
      custom: pack
      arguments: '--no-build -c release $(emgSuffixSwitch)'
      projects: |
        **/ExtensionsMetadataGenerator.csproj

  - task: EsrpCodeSigning@2
    displayName: Sign ExtensionsMetadataGenerator package
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: out/pkg/release
      Pattern: Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator*.nupkg
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetSign",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: CopyFiles@2
    inputs:
      SourceFolder: out/pkg/release
      Contents: '**/*.nupkg'
      TargetFolder: $(Build.ArtifactStagingDirectory)/NugetPackages

  - task: ManifestGeneratorTask@0
    displayName: SBOM generation task - SiteExtension
    inputs:
      BuildDropPath: $(Build.ArtifactStagingDirectory)/SiteExtension
      Verbosity: Information

  - task: ManifestGeneratorTask@0
    displayName: SBOM generation task - PrivateSiteExtension
    inputs:
      BuildDropPath: $(Build.ArtifactStagingDirectory)/PrivateSiteExtension
      Verbosity: Information

  - task: ManifestGeneratorTask@0
    displayName: SBOM generation task - Symbols
    inputs:
      BuildDropPath: $(Build.ArtifactStagingDirectory)/Symbols
      Verbosity: Information

  - task: ManifestGeneratorTask@0
    displayName: SBOM generation task - NugetPackages
    inputs:
      BuildDropPath: $(Build.ArtifactStagingDirectory)/NugetPackages
      Verbosity: Information
