parameters:
- name: description
  type: string
- name: functionAppName
  type: string
- name: instanceId
  type: string
- name: os
  type: string
  default: Windows
  values:
    - Windows
    - Linux
- name: collectPerfViewProfileOnWindows
  type: boolean
  default: false
- name: perfViewCollectArguments
  type: string
  default: ''
- name: collectNetTrace
  type: boolean
  default: false
- name: netTraceCollectArguments
  type: string
- name: createJitTrace
  type: boolean
  default: false

jobs:
- job: ${{ parameters.functionAppName }}_${{ parameters.instanceId }}
  displayName: ${{ parameters.description }} ${{ parameters.instanceId }}
  pool:
    name: 1es-pool-azfunc-benchmarking-large
    ${{ if eq(parameters.os, 'Linux') }}:
      os: linux
      ${{ if and(eq(parameters.createJitTrace, true), eq(parameters.instanceId, '1')) }}:
        image: 1es-ubuntu-22.04-mms-benchmark-coreclr-builder
      ${{ else }}:
        image: 1es-ubuntu-22.04-benchmark-runner-vanilla
    ${{ else }}:
      os: windows
      ${{ if and(eq(parameters.createJitTrace, true), eq(parameters.instanceId, '1')) }}:
        image: 1es-windows-2022-mms-benchmark-coreclr-builder
      ${{ else }}:
        image: 1es-windows-2022-benchmark-runner-vanilla

  variables:
    functionAppOutputPath: $(Build.BinariesDirectory)/Published/HelloHttpNet9
    hostOutputPath: $(Build.BinariesDirectory)/Published/HostRuntime
    logsDirectory: $(Build.ArtifactStagingDirectory)/Logs
    stdOutLogsFilePath: $(logsDirectory)/std_out_logs.txt
    stdErrorLogsFilePath: $(logsDirectory)/std_error_logs.txt
    ${{ if or(eq(parameters.functionAppName, 'HelloHttpNet9'), eq(parameters.functionAppName, 'HelloHttpNet9NoProxy')) }}:
      FUNCTIONS_WORKER_RUNTIME: 'dotnet-isolated'
      FUNCTIONS_WORKER_RUNTIME_VERSION: '9.0'
    ${{ if eq(parameters.functionAppName, 'HelloHttpNode') }}:
      FUNCTIONS_WORKER_RUNTIME: 'node'
      WEBSITE_RUN_FROM_PACKAGE: '1' # Node app needs this to use placeholder channel.
    AzureWebJobsScriptRoot: '$(functionAppOutputPath)'
    perfViewPath: C:\.tools\perfview\perfview.exe 
    traceDirectory: $(Build.ArtifactStagingDirectory)/out
    netTraceDirectory: $(traceDirectory)/nettrace
    traceFileNameWithoutExtension: PerfViewData_$(Build.BuildNumber)_${{ parameters.functionAppName }}
    traceFileName: $(traceFileNameWithoutExtension).etl
    traceFileZipName: $(traceFileName).zip
    traceFilePath: $(traceDirectory)/$(traceFileName)
    traceZipFilePath: $(traceDirectory)/$(traceFileZipName)
    traceAnalysisResultMarkdownFilePath: $(traceDirectory)/results/$(traceFileNameWithoutExtension).md
    traceLogPath: $(logsDirectory)/logs.log
    ${{ if eq(parameters.os, 'Linux') }}:
      publishRid: linux-x64
    ${{ if eq(parameters.os, 'Windows') }}:
      publishRid: win-x64
    ${{ if and(eq(parameters.collectNetTrace, true), eq(parameters.instanceId, '1')) }}:
      netTraceFileNameWithoutExtension: azfunc_${{ parameters.functionAppName }}_${{ parameters.os }}_${{ parameters.instanceId }}
      netTraceFileName: $(netTraceFileNameWithoutExtension).nettrace
      netTraceFilePath: $(netTraceDirectory)/$(netTraceFileName)
      netTraceAnalysisResultsMarkdownFilePath: $(netTraceDirectory)/results/$(netTraceFileNameWithoutExtension).md
      # For JIT trace generation, ensure the trace is collected from an app with authentication enabled (as done by the SLA site).
    ${{ if and(eq(parameters.createJitTrace, true), eq(parameters.instanceId, '1')) }}:
      warmupApiUrl: http://localhost:5000  # For JIT trace generation case, we call the home page instead of the api/warmup endpoint to ensure the host is up and running.
      WEBSITE_SITE_NAME: PGO_${{ parameters.functionAppName }}_${{ parameters.os }}
      benchmarkAppBuildConstants: "-p:DefineConstants=AUTH_FUNCTION" # To publish the function app with authentication enabled.
      functionInvocationUrl: http://localhost:5000/api/HelloAuth?forcespecialization=1&code=test
    ${{ else }}:
      warmupApiUrl: http://localhost:5000/api/warmup?restart=1
      functionInvocationUrl: http://localhost:5000/api/Hello?forcespecialization=1
      benchmarkAppBuildConstants: ""

  ${{ if and(or(eq(parameters.collectPerfViewProfileOnWindows, true), eq(parameters.collectNetTrace, true)), eq(parameters.instanceId, '1')) }}:
    templateContext:
      outputParentDirectory: $(traceDirectory)
      outputs:
        - output: pipelineArtifact
          displayName: Publish Trace artifacts
          path: $(traceDirectory)
          artifact: AzFunc_${{ parameters.os }}_${{ parameters.functionAppName }}
          condition:: always()

  steps:

  - template: /eng/ci/templates/install-dotnet.yml@self

  - script: dotnet --info
    displayName: "Print .NET Environment Info"

  - task: CopyFiles@2
    displayName: Copy benchmark apps to temp location
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/test/Performance/Apps'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/PerformanceTestApps'
      CleanTargetFolder: true

  - task: DotNetCoreCLI@2
    displayName: Publish benchmark app
    inputs:
      command: publish
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      projects: '$(Build.ArtifactStagingDirectory)/PerformanceTestApps/HelloHttpNet9/HelloHttp.csproj'
      arguments: -c Release -o $(functionAppOutputPath) -f net8.0 -r $(publishRid)
      workingDirectory: $(Build.ArtifactStagingDirectory)/PerformanceTestApps/HelloHttpNet9

  - task: AzureCLI@2
    displayName: "Persist (C#)"
    inputs:
      azureSubscription: $(ServiceConnection)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $exePath = "$(functionAppOutputPath)/HelloHttp.exe"
        $connectionString = "$(ColdStartResultsSqlConnectionString)"
        
        Write-Host "Executing HelloHttpNet9.exe with connection string as argument..."
        & $exePath $connectionString

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(ServiceConnection)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        Write-Host "=== [PowerShell Task] Setting Diagnostic Environment Variables ==="
        $env:COMPlus_ForceLogging = "1"
        $env:COMPlus_LogLevel = "9"
        $env:COMPlus_LogToConsole = "1"

        $dateTimeUtc = [datetimeoffset]::UtcNow
        $query = @"
        INSERT INTO [dbo].ColdStart (DateTimeUtc, OS, Description, Document)
        VALUES ('$dateTimeUtc', 'foo', 'bar', '{}')
        "@

        try {
            Invoke-Sqlcmd -ConnectionString "$(ColdStartResultsSqlConnectionString)" -Query $query
        } catch {
            Write-Host "=== [PowerShell Task] Invoke-Sqlcmd failed ==="
            Write-Host $_.Exception.Message
        }

    displayName: Persist (PS)

