parameters:
- name: WorkerName
  displayName: Worker Name
  type: string

- name: WorkerVersion
  displayName: Worker Version
  type: string

# This is an intermediate repository. We cannot use 'self', as that points to the triggering repo.
# We also cannot use relative paths, as that will point to the 1es repo we extend.
# Instead, we need to re-use the alias defines us with. We will default to 'eng' for now.
# This is a hack to workaround a gap in AzDevOps' template system.
- name: repositoryAlias
  type: string
  default: host

jobs:
- job: RunIntegrationTests
  displayName: Run Integration Tests

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows

  variables:
    test_projects: test/WebJobs.Script.Tests.Integration/WebJobs.Script.Tests.Integration.csproj
    is_release: $[contains(variables['Build.SourceBranch'], 'release/')]
    test_args: -c release --no-build

  steps:
  - checkout: self
    persistCredentials: true
  - template: /eng/ci/templates/install-dotnet.yml@${{ parameters.repositoryAlias }}

  - task: UseNode@1
    inputs:
      version: 22.x

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled

  - script: |
      npm install -g azurite
    displayName: Install Azurite

  - task: PowerShell@2
    displayName: Install Az.Storage Powershell module
    inputs:
      targetType: inline
      script: 'Install-Module -Name Az.Storage -RequiredVersion 1.11.0 -Scope CurrentUser -Force -AllowClobber'

  - task: AzurePowerShell@5
    displayName: Checkout secrets
    inputs:
      azureSubscription: Azure-Functions-Host-CI-internal
      azurePowerShellVersion: 'LatestVersion'
      targetType: 'inline'
      pwsh: true
      script: |
          Write-Host "print 1"
          function AcquireLease($blob) {
            try {
              return $blob.ICloudBlob.AcquireLease($null, $null, $null, $null, $null)
            } catch {
              Write-Host "  Error: $_"
              return $null
            } 
          }
          Write-Host "print 2"

          # use this for tracking metadata in lease blobs
          $buildName = "3.0." + $env:buildNumber + "_" + $env:SYSTEM_JOBDISPLAYNAME

          Import-Module Az.Storage

          # get a blob lease to prevent test overlap
          $storageContext = New-AzStorageContext -StorageAccountName "azurefunctionshostci0" -UseConnectedAccount

          While($true) {
            $blobs = Get-AzStorageBlob -Context $storageContext -Container "ci-locks"
            $token = $null
            
            # shuffle the blobs for random ordering
            $blobs = $blobs | Sort-Object {Get-Random}

            Write-Host "Looking for unleased ci-lock blobs (list is shuffled):"
            Foreach ($blob in $blobs) {
              $name = $blob.Name
              $leaseStatus = $blob.ICloudBlob.Properties.LeaseStatus
              
              Write-Host "  ${name}: $leaseStatus"
              
              if ($leaseStatus -eq "Locked") {
                continue
              }

              Write-Host "  Attempting to acquire lease on $name."
              $token = AcquireLease $blob
              if ($token -ne $null) {
                Write-Host "  Lease acquired on $name. LeaseId: '$token'"
                Write-Host "##vso[task.setvariable variable=LeaseBlob]$name"
                Write-Host "##vso[task.setvariable variable=LeaseToken]$token"
                try {
                  $blob.ICloudBlob.FetchAttributes()
                  $blob.ICloudBlob.Metadata["Build"] = $buildName
                  $accessCondition = New-Object -TypeName Microsoft.Azure.Storage.AccessCondition
                  $accessCondition.LeaseId = $token
                  $blob.ICloudBlob.SetMetadata($accessCondition)
                } catch {
                  # best effort
                  Write-Host "Warning: unable to update blob metadata. Continuing. $_"
                }
                break
              } else {
                Write-Host "  Lease not acquired on $name."
              }    
            }
            
            if ($token -ne $null) {
              break
            }
            
            $delay = 30
            Write-Host "No lease acquired. Waiting $delay seconds to try again. This run cannot begin until it acquires a lease on a CI test environment."
            Start-Sleep -s $delay
            Write-Host ""
          }

  - task: AzureKeyVault@1
    inputs:
      # Note: This is actually a Service Connection in DevOps, not an Azure subscription name
      azureSubscription: Azure-Functions-Host-CI-internal
      keyVaultName: azure-functions-host-$(LeaseBlob)
      secretsFilter: '*'

  - task: PowerShell@2
    displayName: Set environment variables
    inputs:
      targetType: inline
      script: |
        Write-Host "##vso[task.setvariable variable=ConnectionStrings__CosmosDB]$env:CosmosDbSecretMap"
        Write-Host "##vso[task.setvariable variable=AzureWebJobsEventHubSender]$env:AzureWebJobsEventHubSenderSecretMap"
        Write-Host "##vso[task.setvariable variable=AzureWebJobsEventHubReceiver]$env:AzureWebJobsEventHubReceiverSecretMap"
        Write-Host "##vso[task.setvariable variable=AzureWebJobsEventHubPath]testhub"
    env:
      AzureWebJobsStorageSecretMap: $(Storage)
      AzureWebJobsSecondaryStorageSecretMap: $(SecondaryStorage)
      CosmosDbSecretMap: $(CosmosDb)
      AzureWebJobsEventHubSenderSecretMap: $(EventHub)
      AzureWebJobsEventHubReceiverSecretMap: $(EventHub)

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: custom
      custom: restore
      arguments: -v m -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      arguments: -v m -c release --no-restore -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: C# end to end tests
    inputs:
      command: test
      testRunTitle: C# end to end tests
      arguments: '--filter "Group=CSharpEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Node end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Node end to end tests
      arguments: '--filter "Group=NodeEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Direct load end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Direct load end to end tests
      arguments: '--filter "Group=DirectLoadEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: F# end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: F# end to end tests
      arguments: '--filter "Group=FSharpEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Language worker end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Language worker end to end tests
      arguments: '--filter "Group=LanguageWorkerSelectionEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Node script host end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Node script host end to end tests
      arguments: '--filter "Group=NodeScriptHostTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Raw assembly end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Raw assembly end to end tests
      arguments: '--filter "Group=RawAssemblyEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Samples end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Samples end to end tests
      arguments: '--filter "Group=SamplesEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Drain mode end to end tests
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Drain mode end to end tests
      arguments: '--filter "Group=DrainModeEndToEndTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Standby mode end to end tests Windows
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Standby mode end to end tests Windows
      arguments: '--filter "Group=StandbyModeEndToEndTests_Windows" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  # Disabled to unblock in 202401. Will fix shortly.
  # - task: DotNetCoreCLI@2
  #   displayName: Standby mode end to end tests Linux
  #   condition: succeededOrFailed()
  #   inputs:
  #     command: test
  #     testRunTitle: Standby mode end to end tests Linux
  #     arguments: '--filter "Group=StandbyModeEndToEndTests_Linux" $(test_args)'
  #     projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Linux container end to end tests Windows
    condition: succeededOrFailed()
    inputs:
      command: test
      testRunTitle: Linux container end to end tests Windows
      arguments: '--filter "Group=ContainerInstanceTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Release verification tests
    condition: ${{ eq(variables.is_release, true) }}
    inputs:
      command: test
      testRunTitle: Release verification tests
      arguments: '--filter "Group=ReleaseTests" $(test_args) -p:WorkerVersion=${{ parameters.WorkerVersion }} -p:WorkerName=${{ parameters.WorkerName }}'
      projects: $(test_projects)

  - task: AzurePowerShell@5
    condition: always()
    displayName: Checkin secrets
    inputs:
      azureSubscription: Azure-Functions-Host-CI-internal
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true
      ScriptPath: eng/script/checkin-secrets.ps1
      ScriptArguments: '-leaseBlob $(LeaseBlob) -leaseToken $(LeaseToken)'
