parameters:
- name: public
  displayName: Publish to nuget.org?
  type: boolean
  default: false

trigger: none
pr: none

extends:
  template: /eng/ci/templates/official/pipelines/release.yml@self
  parameters:
    public: ${{ parameters.public }}
    folder: azure-webjobs-script-abstractions
    projects: |
      $(Build.SourcesDirectory)/src/WebJobs.Script.Abstractions/WebJobs.Script.Abstractions.csproj
      $(Build.SourcesDirectory)/test/WebJobs.Script.Abstractions.Tests/WebJobs.Script.Abstractions.Tests.csproj
