name: AzFunc.Host - Code Mirror

trigger:
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/inproc6/4.*
    - release/inproc8/4.*

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
