trigger:
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/in-proc

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/heads/u/jviau/mirror-sdl

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
