trigger: none

pr:
  branches:
    include:
    - v1.x
    - release/1.*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /ci/variables/cfs.yml@eng
  - template: /eng/ci/templates/variables/build.yml@self
  - name: includeBuildNumberInVersion
    value: 1
  - name: configuration
    value: Release
  - name: test_results_path
    value: '$(System.DefaultWorkingDirectory)\test-results'

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022 
      os: windows

    stages:
    - stage: Test
      jobs:
        steps:
          - template: /eng/ci/templates/steps/build.yml@self
            parameters:
              configuration: $(configuration)
              targets: TestBuild

          - template: /eng/ci/templates/steps/test.yml@self
            parameters:
              configuration: $(configuration)
              results_path: $(test_results_path)
              filter: 'Integration'
