trigger:
  batch: true
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/in-proc

schedules:
# Ensure we build nightly to catch any new CVEs and report SDL often.
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
    - dev
    - in-proc
  always: true

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self
  - template: /ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
        # Move codeql for source languages to source analysis stage
        runSourceLanguagesInSourceAnalysis: true

    stages:
    - stage: Build

      jobs:
      - template: /eng/ci/templates/official/jobs/build-artifacts-windows.yml@self
      - template: /eng/ci/templates/official/jobs/build-artifacts-linux.yml@self

    - stage: Test

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
      - template: /eng/ci/templates/official/jobs/run-non-e2e-tests.yml@self
      - template: /eng/ci/templates/official/jobs/run-integration-tests.yml@self
