

trigger:
  batch: true
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/inproc6/4.*
    - release/inproc8/4.*

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/build.yml@eng
  - template: ci/variables/cfs.yml@eng
  - name: buildNumber
    value: $[ counter('constant', 13000) ] # TODO: new pipeline, 13000 no longer valid.
  - name: minorVersionPrefix
    ${{ if contains(variables['Build.SourceBranch'], 'release/inproc6/') }}:
      value: "6"
    ${{ elseif contains(variables['Build.SourceBranch'], 'release/inproc8/') }}:
      value: "8"
    ${{ else }}:
      value: ""

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Initialize

      jobs:
      - template: /eng/ci/templates/jobs/initialize-pipeline.yml@self
        parameters:
          minorVersionPrefix: ${{ variables.minorVersionPrefix }}

    - stage: Build
      dependsOn: Initialize

      jobs:
      - template: /eng/ci/templates/official/jobs/build-artifacts-windows.yml@self
        parameters:
          minorVersionPrefix: ${{ variables.minorVersionPrefix }}

      - template: /eng/ci/templates/official/jobs/build-artifacts-linux.yml@self
        parameters:
          minorVersionPrefix: ${{ variables.minorVersionPrefix }}

    - stage: Test
      dependsOn: Initialize

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
      # TODO: commented out while iterating on other steps
      # - template: /eng/ci/templates/official/jobs/run-non-e2e-tests.yml@self
      # - template: /eng/ci/templates/official/jobs/run-integration-tests.yml@self
