# This build is used for public PR and CI builds.

variables:
  buildNumber: $[ counter('constant', 23000) ] # 23000 selected to be ahead of current host build
  ${{ if contains(variables['Build.SourceBranch'], 'release/inproc6/') }}:
    minorVersionPrefix: "6"
  ${{ elseif contains(variables['Build.SourceBranch'], 'release/inproc8/') }}:
    minorVersionPrefix: "8"
  ${{ else }}:
    minorVersionPrefix: ""
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

trigger:
  batch: true
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/inproc6/4.*
    - release/inproc8/4.*

pr:
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/inproc6/4.*
    - release/inproc8/4.*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Initialize

      jobs:
      - template: /eng/ci/templates/jobs/initialize-pipeline.yml@self
        parameters:
          minorVersionPrefix: ${{ variables.minorVersionPrefix }}

    - stage: Test
      dependsOn: Initialize

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
