trigger:
  branches:
    include:
    - v1.x
    - release/1.*

pr:
  branches:
    include:
    - v1.x
    - release/1.*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: BuildAndTest

      jobs:
      - job: BuildAndTest
        templateContext:
          outputParentDirectory: $(publish_path)
          outputs:
          - output: pipelineArtifact
            displayName: Publish drop
            path: $(publish_path)/Packages
            artifact: drop

        steps:
          - template: /eng/ci/templates/steps/build.yml@self
            parameters:
              configuration: $(configuration)
              publish_path: $(publish_path)
              build_number: $(build_number)

          - template: /eng/ci/templates/steps/test.yml@self
            parameters:
              configuration: $(configuration)
              results_path: $(test_results_path)
              filter: Unit
