# This build is used for public PR and CI builds.

variables:
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

trigger:
  batch: true
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/in-proc

pr:
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/in-proc

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Run Tests
      jobs:
      - template: /eng/ci/templates/jobs/initialize-pipeline.yml@self
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
