parameters:
- name: sign
  type: boolean
  default: false
- name: projects
  type: string
- name: configuration
  type: string
  default: release
- name: build_args
  type: string
  default: ''
- name: label
  type: string
  default: ''

jobs:
- job: ${{ iif(eq(parameters.label, ''), 'build', format('build_{0}', parameters.label)) }}
  displayName: ${{ iif(eq(parameters.label, ''), 'Build', format('Build ({0})', parameters.label)) }}

  variables:
  - template: /eng/ci/templates/variables/build.yml@self
  - name: pack_dir
    readonly: true
    value: $(Build.ArtifactStagingDirectory)/pkg

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish packages
      path: $(pack_dir)
      artifact: ${{ iif(eq(parameters.label, ''), 'drop_packages', format('drop_packages_{0}', parameters.label)) }}

  steps:
    - template: /eng/ci/templates/install-dotnet.yml@self

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: custom
        custom: restore
        projects: ${{ parameters.projects }}
        arguments: -v m ${{ parameters.build_args }}

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: ${{ parameters.projects }}
        arguments: -c ${{ parameters.configuration }} -v m --no-restore ${{ parameters.build_args }}

    - task: DotNetCoreCLI@2
      displayName: Unit tests
      inputs:
        command: test
        arguments: -c ${{ parameters.configuration }} --no-build ${{ parameters.build_args }}
        projects: ${{ parameters.projects }}

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign assemblies
          minimatch: true
          signType: dll
          folderPath: out/bin
          pattern: |
            **/Microsoft.Azure.WebJobs.*.dll
            !**/*Test*.dll

    - task: DotNetCoreCLI@2
      displayName: Pack
      inputs:
        command: custom
        custom: pack
        arguments: -c ${{ parameters.configuration }} -v m -o $(pack_dir) --no-build ${{ parameters.build_args }}
        projects: ${{ parameters.projects }}

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign nuget packages
          signType: nuget
          folderPath: $(pack_dir)
          pattern: Microsoft.Azure.WebJobs.*.nupkg

      - task: DeleteFiles@1
        displayName: Delete CodeSignSummary files
        inputs:
          contents: $(pack_dir)/CodeSignSummary-*.md
