jobs:
  - job: InitializePipeline
    displayName: Initialize Pipeline

    templateContext:
      sdl:
        codeql:
          compiled:
            enabled: false

    steps:
    - task: UseDotNet@2 # The pinned SDK we use to build
      displayName: 'Install .NET SDK from global.json'
      inputs:
        packageType: sdk
        useGlobalJson: true

    - task: PowerShell@2
      displayName: 'Initialize'
      name: Initialize
      inputs:
        filePath: build/initialize-pipeline.ps1
        showWarnings: true
        pwsh: true
