parameters:
  - name: minorVersionPrefix
    type: string
    default: ''

jobs:
  - job: InitializePipeline
    displayName: Initialize Pipeline

    steps:
    - task: UseDotNet@2 # The pinned SDK we use to build
      displayName: 'Install .NET SDK from global.json'
      inputs:
        packageType: sdk
        useGlobalJson: true

    - task: PowerShell@2
      displayName: 'Initialize'
      name: Initialize
      inputs:
        filePath: /build/initialize-pipeline.ps1
        arguments: -minorVersionPrefix "$(minorVersionPrefix)"
        showWarnings: true
        pwsh: true
