jobs:
- job: RunUnitTests
  displayName: Run Unit Tests

  variables:
  - name: test_projects
    value: |
      **\ExtensionsMetadataGeneratorTests.csproj
      **\WebJobs.Script.Tests.csproj
  - name: log_dir
    value: $(Build.ArtifactStagingDirectory)/log

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish logs
      path: $(log_dir)
      artifact: Unit_Test_Log
      sbomEnabled: false
      condition: always()

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: custom
      custom: restore
      arguments: -v m -bl:$(log_dir)/restore.binlog
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      arguments: -v m -c release --no-restore -bl:$(log_dir)/build.binlog
      projects: $(test_projects)

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: test
      testRunTitle: Unit Tests
      arguments: -v m -c release --no-build
      projects: $(test_projects)
