jobs:
- job: RunUnitTests
  displayName: Run Unit Tests

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    # We publish this deps.json as differences in exact dotnet SDK version between dev and CI may make it impossible to generate locally.
    - output: pipelineArtifact
      displayName: Publish deps.json
      path: $(Build.ArtifactStagingDirectory)
      artifact: WebHost_Deps

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: test
      testRunTitle: Unit Tests
      arguments: -v n
      projects: |
        **\ExtensionsMetadataGeneratorTests.csproj
        **\WebJobs.Script.Tests.csproj

  - task: CopyFiles@2
    displayName: Copy deps.json
    condition: always()
    inputs:
      SourceFolder: out/bin/WebJobs.Script.WebHost/debug
      Contents: '**/*.deps.json'
      TargetFolder: $(Build.ArtifactStagingDirectory)
