jobs:
- job: RunUnitTests
  displayName: Run Unit Tests

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: test
      testRunTitle: Unit Tests
      arguments: -v n
      projects: |
        **\WebJobs.Script.Scaling.Tests.csproj
        **\WebJobs.Script.Tests.csproj
