// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Microsoft.Azure.WebJobs.Script.Benchmarks")]
[assembly: InternalsVisibleTo("Microsoft.Azure.WebJobs.Script.Tests")]
[assembly: InternalsVisibleTo("Microsoft.Azure.WebJobs.Script.Tests.Integration")]

// This assembly is the default dynamic assembly generated by Castle DynamicProxy used by Moq.
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]