trigger: none
variables:
- group: HotfixDefaultSecrets
stages:
- stage: Run
  jobs:
  - job: Create hotfix tags
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: './$(System.DefaultWorkingDirectory)/_Azure_azure-functions-host/.scripts/DetectHotfixHostVersions.ps1'