<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Azure.Functions.Rpc.Client</PackageId>
    <AssemblyName>Azure.Functions.Rpc.Client</AssemblyName>
    <RootNamespace>Azure.Functions.Rpc.Client</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebJobs.Script.Grpc\WebJobs.Script.Grpc.csproj" />
    <ProjectReference Include="..\WebJobs.Script\WebJobs.Script.csproj" />
  </ItemGroup>

</Project>
