<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Azure.Functions.WorkerProxy</AssemblyName>
    <RootNamespace>Azure.Functions.WorkerProxy</RootNamespace>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" VersionOverride="3.35.1" />
    <PackageReference Include="Grpc.AspNetCore" VersionOverride="2.76.0" />
    <PackageReference Include="Grpc.Core.Api" VersionOverride="2.76.0" />
    <PackageReference Include="Grpc.Net.Client" VersionOverride="2.76.0" />
    <PackageReference Include="Grpc.Tools" VersionOverride="2.76.0" PrivateAssets="all" />
    <PackageReference Include="Yarp.ReverseProxy" VersionOverride="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Azure.Functions.WorkerProxy.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf
      Include="..\WebJobs.Script.Grpc\azure-functions-language-worker-protobuf\src\proto\**\*.proto"
      GrpcServices="server"
      ProtoRoot="..\WebJobs.Script.Grpc\azure-functions-language-worker-protobuf\src\proto" />
  </ItemGroup>

</Project>
