// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;

namespace Microsoft.Azure.WebJobs.Script.PublicApi.Tests;

/// <summary>
/// Builds the deterministic compiled public API snapshot of a shipped first-party assembly.
/// </summary>
internal static class PublicApiSnapshotBuilder
{
    /// <summary>
    /// The binding flags used to enumerate every declared member, including protected members.
    /// </summary>
    public const BindingFlags DeclaredMembers =
        BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

    private static readonly string[] BaselineBanner =
    {
        "# Compiled public API baseline. Generated by test/WebJobs.Script.PublicApi.Tests.",
        "# Do not edit by hand: run eng/script/update-public-api-baselines.ps1 after an approved API change.",
        "# Format: <kind> | <identity> | <signature>. '!' marks a non-nullable and '?' a nullable reference type."
    };

    /// <summary>
    /// Loads an assembly from its exact build output path into an isolated load context.
    /// </summary>
    /// <param name="assemblyPath">The absolute path of the assembly to load.</param>
    /// <param name="probeDirectories">Additional directories used to resolve dependencies.</param>
    /// <returns>The isolated load context, already holding the requested assembly.</returns>
    public static PublicApiAssemblyLoadContext LoadInContext(string assemblyPath, IReadOnlyList<string> probeDirectories)
    {
        if (!File.Exists(assemblyPath))
        {
            throw new FileNotFoundException(
                $"The Release build output '{assemblyPath}' does not exist. Build the shipped projects in Release before running the public API gate.",
                assemblyPath);
        }

        var context = new PublicApiAssemblyLoadContext(assemblyPath, probeDirectories);
        context.LoadFromAssemblyPath(assemblyPath);

        return context;
    }

    /// <summary>
    /// Loads an assembly from its exact build output path into an isolated load context and snapshots its API.
    /// </summary>
    /// <param name="assemblyPath">The absolute path of the assembly to inspect.</param>
    /// <param name="probeDirectories">Additional directories used to resolve dependencies.</param>
    /// <returns>The compiled public API snapshot.</returns>
    public static PublicApiSnapshot Create(string assemblyPath, IReadOnlyList<string> probeDirectories)
    {
        PublicApiAssemblyLoadContext context = LoadInContext(assemblyPath, probeDirectories);

        return Create(context.LoadFromAssemblyPath(assemblyPath));
    }

    /// <summary>
    /// Snapshots the compiled public API of an already loaded assembly.
    /// </summary>
    /// <param name="assembly">The assembly to inspect.</param>
    /// <returns>The compiled public API snapshot.</returns>
    public static PublicApiSnapshot Create(Assembly assembly)
    {
        AssemblyName name = assembly.GetName();
        var records = new List<PublicApiRecord>
        {
            PublicApiRecord.ForAssembly("name", name.Name),
            PublicApiRecord.ForAssembly("version", name.Version?.ToString() ?? "none"),
            PublicApiRecord.ForAssembly("culture", string.IsNullOrEmpty(name.CultureName) ? "neutral" : name.CultureName),
            PublicApiRecord.ForAssembly("publicKeyToken", FormatPublicKeyToken(name.GetPublicKeyToken())),
            PublicApiRecord.ForAssembly("targetFramework", GetTargetFramework(assembly))
        };

        records.AddRange(GetTypeForwarders(assembly));

        foreach (Type type in GetLoadedTypes(assembly))
        {
            records.AddRange(CreateTypeRecords(type));
        }

        return new PublicApiSnapshot(name.Name, Sort(records));
    }

    /// <summary>
    /// Renders a snapshot as deterministic, line-oriented baseline text using LF line endings.
    /// </summary>
    /// <param name="records">The records to render.</param>
    /// <returns>The baseline file content.</returns>
    public static string Render(IEnumerable<PublicApiRecord> records)
    {
        var builder = new StringBuilder();

        foreach (string line in BaselineBanner)
        {
            builder.Append(line).Append('\n');
        }

        foreach (PublicApiRecord record in Sort(records))
        {
            builder.Append(record.Line).Append('\n');
        }

        return builder.ToString();
    }

    /// <summary>
    /// Reads the comparable records of a rendered baseline, skipping banner comments and blank lines.
    /// </summary>
    /// <param name="content">The baseline file content.</param>
    /// <returns>The baseline record lines in file order.</returns>
    public static IReadOnlyList<string> ReadLines(string content)
    {
        return content
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n')
            .Where(line => line.Length > 0 && !line.StartsWith('#'))
            .ToArray();
    }

    /// <summary>
    /// Sorts records so a type declaration is immediately followed by its own members.
    /// </summary>
    /// <param name="records">The records to sort.</param>
    /// <returns>The deterministically ordered records.</returns>
    public static IReadOnlyList<PublicApiRecord> Sort(IEnumerable<PublicApiRecord> records)
    {
        return records
            .OrderBy(record => record.SortGroup)
            .ThenBy(record => record.DeclaringType, StringComparer.Ordinal)
            .ThenBy(record => KindRank(record.Kind))
            .ThenBy(record => record.Identity, StringComparer.Ordinal)
            .ThenBy(record => record.Signature, StringComparer.Ordinal)
            .ToArray();
    }

    private static IEnumerable<PublicApiRecord> CreateTypeRecords(Type type)
    {
        string accessibility = PublicApiSignatureFormatter.GetEffectiveTypeAccessibility(type);
        if (accessibility is null)
        {
            yield break;
        }

        string typeIdentity = GetTypeIdentity(type);
        yield return new PublicApiRecord(
            "type",
            typeIdentity,
            typeIdentity,
            PublicApiSignatureFormatter.FormatTypeDeclaration(type, accessibility));

        HashSet<MethodInfo> accessors = PublicApiSignatureFormatter.CollectAccessors(type);

        foreach (MemberInfo member in type.GetMembers(DeclaredMembers))
        {
            if (member is Type)
            {
                continue;
            }

            if (member is MethodInfo method && accessors.Contains(method))
            {
                continue;
            }

            if (member is FieldInfo enumValue && type.IsEnum && string.Equals(enumValue.Name, "value__", StringComparison.Ordinal))
            {
                continue;
            }

            string memberAccessibility = PublicApiSignatureFormatter.GetMemberAccessibility(member);
            if (memberAccessibility is null)
            {
                continue;
            }

            yield return CreateMemberRecord(typeIdentity, member, memberAccessibility);
        }
    }

    private static PublicApiRecord CreateMemberRecord(string typeIdentity, MemberInfo member, string accessibility)
    {
        switch (member)
        {
            case ConstructorInfo constructor:
                string constructorIdentity = $"{typeIdentity}.{constructor.Name}({FormatIdentityParameters(constructor.GetParameters())})";
                return new PublicApiRecord(
                    "constructor",
                    typeIdentity,
                    constructorIdentity,
                    PublicApiSignatureFormatter.FormatConstructor(constructor, accessibility));

            case MethodInfo method:
                string methodIdentity = $"{typeIdentity}.{method.Name}{FormatArity(method.GetGenericArguments().Length)}({FormatIdentityParameters(method.GetParameters())})";
                return new PublicApiRecord(
                    "method",
                    typeIdentity,
                    methodIdentity,
                    PublicApiSignatureFormatter.FormatMethod(method, accessibility));

            case PropertyInfo property:
                ParameterInfo[] indexParameters = property.GetIndexParameters();
                string propertyIdentity = indexParameters.Length == 0
                    ? $"{typeIdentity}.{property.Name}"
                    : $"{typeIdentity}.{property.Name}[{FormatIdentityParameters(indexParameters)}]";
                return new PublicApiRecord(
                    "property",
                    typeIdentity,
                    propertyIdentity,
                    PublicApiSignatureFormatter.FormatProperty(property, accessibility));

            case EventInfo eventInfo:
                return new PublicApiRecord(
                    "event",
                    typeIdentity,
                    $"{typeIdentity}.{eventInfo.Name}",
                    PublicApiSignatureFormatter.FormatEvent(eventInfo, accessibility));

            case FieldInfo field:
                return new PublicApiRecord(
                    "field",
                    typeIdentity,
                    $"{typeIdentity}.{field.Name}",
                    PublicApiSignatureFormatter.FormatField(field, accessibility));

            default:
                throw new InvalidOperationException($"Unsupported member kind '{member.MemberType}' on '{typeIdentity}'.");
        }
    }

    private static IEnumerable<PublicApiRecord> GetTypeForwarders(Assembly assembly)
    {
        return assembly.GetForwardedTypes()
            .Select(forwarded => new PublicApiRecord(
                "forwarder",
                string.Empty,
                forwarded.FullName ?? forwarded.Name,
                forwarded.Assembly.GetName().Name))
            .OrderBy(record => record.Identity, StringComparer.Ordinal)
            .ToArray();
    }

    private static IEnumerable<Type> GetLoadedTypes(Assembly assembly)
    {
        Type[] types;

        try
        {
            types = assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException exception)
        {
            string details = string.Join(
                Environment.NewLine,
                exception.LoaderExceptions
                    .Where(loaderException => loaderException is not null)
                    .Select(loaderException => "  " + loaderException.Message)
                    .Distinct(StringComparer.Ordinal)
                    .OrderBy(message => message, StringComparer.Ordinal)
                    .Take(20));

            throw new InvalidOperationException(
                $"Unable to load every type of '{assembly.GetName().Name}'. A partial snapshot would silently drop public API.{Environment.NewLine}{details}",
                exception);
        }

        return types
            .Where(type => !string.Equals(type.Name, "<Module>", StringComparison.Ordinal))
            .OrderBy(type => type.FullName ?? type.Name, StringComparer.Ordinal);
    }

    private static string FormatIdentityParameters(ParameterInfo[] parameters)
    {
        return string.Join(",", parameters.Select(parameter =>
        {
            string name = PublicApiSignatureFormatter.FormatTypeName(parameter.ParameterType, nullability: null);
            return parameter.ParameterType.IsByRef ? name + "&" : name;
        }));
    }

    private static string FormatArity(int arity)
    {
        return arity == 0 ? string.Empty : "`" + arity.ToString(CultureInfo.InvariantCulture);
    }

    private static string GetTypeIdentity(Type type)
    {
        var segments = new List<string>();

        for (Type current = type; current is not null; current = current.DeclaringType)
        {
            segments.Insert(0, current.Name);

            if (!current.IsNested)
            {
                if (!string.IsNullOrEmpty(current.Namespace))
                {
                    segments.Insert(0, current.Namespace);
                }

                break;
            }
        }

        return string.Join(".", segments);
    }

    private static string GetTargetFramework(Assembly assembly)
    {
        return assembly.CustomAttributes
            .Where(attribute => string.Equals(
                attribute.AttributeType.FullName,
                "System.Runtime.Versioning.TargetFrameworkAttribute",
                StringComparison.Ordinal))
            .Select(attribute => attribute.ConstructorArguments.Count > 0 ? attribute.ConstructorArguments[0].Value as string : null)
            .FirstOrDefault(value => !string.IsNullOrEmpty(value))
            ?? "none";
    }

    private static string FormatPublicKeyToken(byte[] token)
    {
        return token is null || token.Length == 0
            ? "null"
            : string.Concat(token.Select(value => value.ToString("x2", CultureInfo.InvariantCulture)));
    }

    private static int KindRank(string kind)
    {
        return kind switch
        {
            "assembly" => 0,
            "forwarder" => 1,
            "type" => 2,
            "constructor" => 3,
            "field" => 4,
            "property" => 5,
            "event" => 6,
            "method" => 7,
            _ => 8
        };
    }
}

/// <summary>
/// A single canonical compiled public API record.
/// </summary>
internal sealed class PublicApiRecord
{
    private const string Separator = " | ";

    public PublicApiRecord(string kind, string declaringType, string identity, string signature)
    {
        Kind = kind;
        DeclaringType = declaringType;
        Identity = identity;
        Signature = signature;
    }

    /// <summary>
    /// Gets the record kind, such as <c>type</c>, <c>method</c>, or <c>assembly</c>.
    /// </summary>
    public string Kind { get; }

    /// <summary>
    /// Gets the identity of the declaring type, or an empty string for assembly-level records.
    /// </summary>
    public string DeclaringType { get; }

    /// <summary>
    /// Gets the unique identity of the record within its assembly.
    /// </summary>
    public string Identity { get; }

    /// <summary>
    /// Gets the canonical signature text.
    /// </summary>
    public string Signature { get; }

    /// <summary>
    /// Gets the rendered baseline line.
    /// </summary>
    public string Line => Kind + Separator + Identity + Separator + Signature;

    /// <summary>
    /// Gets the group used to keep assembly identity records at the top of a baseline.
    /// </summary>
    public int SortGroup => Kind switch
    {
        "assembly" => 0,
        "forwarder" => 1,
        _ => 2
    };

    /// <summary>
    /// Creates an assembly identity record.
    /// </summary>
    /// <param name="name">The identity field name.</param>
    /// <param name="value">The identity field value.</param>
    /// <returns>The record.</returns>
    public static PublicApiRecord ForAssembly(string name, string value)
    {
        return new PublicApiRecord("assembly", string.Empty, name, value);
    }

    /// <summary>
    /// Gets the relaxed key used to pair a removed record with its replacement.
    /// </summary>
    /// <param name="line">The rendered baseline line.</param>
    /// <returns>The relaxed change key.</returns>
    public static string GetChangeKey(string line)
    {
        string[] parts = line.Split(Separator, 3, StringSplitOptions.None);
        if (parts.Length < 3)
        {
            return line;
        }

        string identity = parts[1];
        int cut = identity.IndexOfAny(new[] { '(', '[' });
        if (cut >= 0)
        {
            identity = identity[..cut];
        }

        int arity = identity.LastIndexOf('`');
        if (arity >= 0)
        {
            identity = identity[..arity];
        }

        return parts[0] + Separator + identity;
    }
}

/// <summary>
/// The compiled public API snapshot of one assembly.
/// </summary>
internal sealed class PublicApiSnapshot
{
    public PublicApiSnapshot(string assemblyName, IReadOnlyList<PublicApiRecord> records)
    {
        AssemblyName = assemblyName;
        Records = records;

        string[] duplicates = records
            .GroupBy(record => record.Line, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .OrderBy(line => line, StringComparer.Ordinal)
            .ToArray();

        if (duplicates.Length > 0)
        {
            throw new InvalidOperationException(
                $"'{assemblyName}' produced duplicate public API records, so added/removed reporting would be ambiguous:{Environment.NewLine}"
                + string.Join(Environment.NewLine, duplicates.Select(line => "  " + line)));
        }
    }

    /// <summary>
    /// Gets the simple assembly name.
    /// </summary>
    public string AssemblyName { get; }

    /// <summary>
    /// Gets the deterministically ordered records.
    /// </summary>
    public IReadOnlyList<PublicApiRecord> Records { get; }

    /// <summary>
    /// Gets the rendered baseline lines.
    /// </summary>
    public IReadOnlyList<string> Lines => Records.Select(record => record.Line).ToArray();
}

/// <summary>
/// Loads an inspected assembly and its dependencies without polluting the default load context.
/// </summary>
internal sealed class PublicApiAssemblyLoadContext : AssemblyLoadContext
{
    private readonly AssemblyDependencyResolver _resolver;
    private readonly string[] _probeDirectories;

    public PublicApiAssemblyLoadContext(string assemblyPath, IReadOnlyList<string> probeDirectories)
        : base($"PublicApi:{Path.GetFileNameWithoutExtension(assemblyPath)}", isCollectible: false)
    {
        _resolver = new AssemblyDependencyResolver(assemblyPath);
        _probeDirectories = new[] { Path.GetDirectoryName(assemblyPath) }
            .Concat(probeDirectories)
            .Where(directory => !string.IsNullOrEmpty(directory) && Directory.Exists(directory))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    protected override Assembly Load(AssemblyName assemblyName)
    {
        string resolved = _resolver.ResolveAssemblyToPath(assemblyName);
        if (!string.IsNullOrEmpty(resolved) && File.Exists(resolved))
        {
            return LoadFromAssemblyPath(resolved);
        }

        Assembly platformAssembly = Default.Assemblies.FirstOrDefault(candidate =>
            AssemblyName.ReferenceMatchesDefinition(candidate.GetName(), assemblyName));
        if (platformAssembly is not null)
        {
            return platformAssembly;
        }

        foreach (string directory in _probeDirectories)
        {
            string candidate = Path.Combine(directory, assemblyName.Name + ".dll");
            if (File.Exists(candidate))
            {
                return LoadFromAssemblyPath(candidate);
            }
        }

        return null;
    }

    protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
    {
        string resolved = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
        return string.IsNullOrEmpty(resolved) ? IntPtr.Zero : LoadUnmanagedDllFromPath(resolved);
    }
}
